from datetime import date

 

Toyota_RAV4_2010 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY10"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,4l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "04/2010"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "130 kW (177 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2010"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNHZkIic03_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNHZkIic03_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNHZkIic03_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNHZkIic03_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsmeSqA8eBo",
    "model": "RAV4",
    "price": 6000000,
    "kilometrage": 160000,
    "carburant": "Diesel",
    "annee": date(2010, 4, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "130 kW (177 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 500 kg"],
    ],
}

Toyota_RAV4_2011 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,0l/100 km (mixte)"],
        ["Émissions de CO2", "185 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "135 kW (184 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "06/2011"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2011_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2011_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2011_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2011_Rouge_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsqRJPXkpGL",
    "model": "RAV4",
    "price": 6200000,
    "kilometrage": 150000,
    "carburant": "Essence",
    "annee": date(2011, 6, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "135 kW (184 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}

Toyota_RAV4_2012 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2012"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "07/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2012_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2012_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2012_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2012_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carst30wkFMrv",
    "model": "RAV4",
    "price": 6400000,
    "kilometrage": 140000,
    "carburant": "Diesel",
    "annee": date(2012, 7, 1),
    "carosserie":"SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": "Gris",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 600 kg"],
    ],
}

Toyota_RAV4_2013 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "09/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsKcT6xQkLo_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsKcT6xQkLo_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsKcT6xQkLo_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsKcT6xQkLo_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carscs3UtANus",
    "model": "RAV4",
    "price": 6600000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2013, 9, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Bleu",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 650 kg"],
    ],
}

Toyota_RAV4_2014 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "11/2014"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "155 kW (211 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "11/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2014_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2014_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2014_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2014_Rouge_04.jpg"
    ],
    "mark": "Toyota",
    "webid":  "Carsis_cars3t733Cx8Z",
    "model": "RAV4",
    "price": 6800000,
    "kilometrage": 120000,
    "carburant": "Diesel",
    "annee": date(2014, 11, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "155 kW (211 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Toyota_RAV4_2015 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY15"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2015"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "165 kW (224 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "02/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2015_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2015_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2015_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2015_Blanc_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsu5sI8klnn",
    "model": "RAV4",
    "price": 7000000,
    "kilometrage": 110000,
    "carburant": "Essence",
    "annee": date(2015, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "165 kW (224 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Toyota_RAV4_2016 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY16"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "100 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2016"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "170 kW (231 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "100 000 km"],
        ["Année", "02/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsz9eBhpdeX_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsz9eBhpdeX_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsz9eBhpdeX_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsz9eBhpdeX_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carslp0r1pIMf",
    "model": "RAV4",
    "price": 7500000,
    "kilometrage": 100000,
    "carburant": "Diesel",
    "annee": date(2016, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "170 kW (231 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Toyota_RAV4_2017 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY17"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,2l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "90 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2017"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "180 kW (245 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "90 000 km"],
        ["Année", "02/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2017_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2017_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2017_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2017_Blanc_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsisphAUnLt",
    "model": "RAV4",
    "price": 7800000,
    "kilometrage": 90000,
    "carburant": "Essence",
    "annee": date(2017, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "180 kW (245 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 750 kg"],
    ],
}

Toyota_RAV4_2018 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY18"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
        ["Système audio premium", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "80 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2018"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "185 kW (252 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "80 000 km"],
        ["Année", "03/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2018_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2018_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2018_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2018_Rouge_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsF1LT8wtCS",
    "model": "RAV4",
    "price": 8200000,
    "kilometrage": 80000,
    "carburant": "Diesel",
    "annee": date(2018, 3, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "185 kW (252 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 900 kg"],
    ],
}

Toyota_RAV4_2019 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY19"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "140 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
        ["Système audio premium", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "70 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2019"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "190 kW (258 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "70 000 km"],
        ["Année", "03/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2019_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2019_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2019_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Toyota_RAV4_2019_Noir_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsMAlCJKfHm",
    "model": "RAV4",
    "price": 8500000,
    "kilometrage": 70000,
    "carburant": "Essence",
    "annee": date(2019, 3, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "190 kW (258 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 850 kg"],
    ],
}

Toyota_RAV4_2020 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY20"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,0l/100 km (mixte)"],
        ["Émissions de CO2", "140 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
        ["Système audio premium", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "60 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2020"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "195 kW (264 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "60 000 km"],
        ["Année", "03/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carskrcNw4GXS_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carskrcNw4GXS_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carskrcNw4GXS_03.jpg"
    ],
    "mark": "Toyota",
    "webid":  "Carsis_carsFsuv8xlna",
    "model": "RAV4",
    "price": 8800000,
    "kilometrage": 60000,
    "carburant": "Diesel",
    "annee": date(2020, 3, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "195 kW (264 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 900 kg"],
    ],
}


Toyota_RAV_4=[Toyota_RAV4_2010,Toyota_RAV4_2013,Toyota_RAV4_2016,Toyota_RAV4_2020]