from datetime import date


Toyota_CAMRY_2009 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY09"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "200 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "170 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2009"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "119 kW (160 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "170 000 km"],
        ["Année", "03/2009"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrN2BWu6Pp_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrN2BWu6Pp_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrN2BWu6Pp_03.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsrN2BWu6Pp",
    "model": "CAMRY",
    "price": 8000000,
    "kilometrage": 170000,
    "carburant": "Essence",
    "annee": date(2009, 3, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.4L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "119 kW (160 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 465 kg"],
    ],
}

Toyota_CAMRY_2010 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY10"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,3l/100 km (mixte)"],
        ["Émissions de CO2", "195 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "165 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2010"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "119 kW (160 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "165 000 km"],
        ["Année", "05/2010"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2010_1.jpg",
        "https://example.com/camry_2010_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsfWLptDVOe",
    "model": "CAMRY",
    "price": 8500000,
    "kilometrage": 165000,
    "carburant": "Essence",
    "annee": date(2010, 5, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.4L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "119 kW (160 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 470 kg"],
    ],
}


Toyota_CAMRY_2011 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,1l/100 km (mixte)"],
        ["Émissions de CO2", "190 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "119 kW (160 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2011"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2011_1.jpg",
        "https://example.com/camry_2011_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carso0n0NiL7d",
    "model": "CAMRY",
    "price": 8700000,
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2011, 4, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.4L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "119 kW (160 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 480 kg"],
    ],
}

Toyota_CAMRY_2012 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,8l/100 km (mixte)"],
        ["Émissions de CO2", "185 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "07/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2012_1.jpg",
        "https://example.com/camry_2012_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsmx174agIO",
    "model": "CAMRY",
    "price": 9000000,
    "kilometrage": 150000,
    "carburant": "Essence",
    "annee": date(2012, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 490 kg"],
    ],
}

Toyota_CAMRY_2013 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "180 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "09/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseun6ThN5I_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseun6ThN5I_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseun6ThN5I_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseun6ThN5I_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carseun6ThN5I",
    "model": "CAMRY",
    "price": 9200000,
    "kilometrage": 140000,
    "carburant": "Essence",
    "annee": date(2013, 9, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 500 kg"],
    ],
}

Toyota_CAMRY_2014 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,3l/100 km (mixte)"],
        ["Émissions de CO2", "175 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "11/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "11/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2014_1.jpg",
        "https://example.com/camry_2014_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsP3yO19MGE",
    "model": "CAMRY",
    "price": 9500000,
    "kilometrage": 140000,
    "carburant": "Essence",
    "annee": date(2014, 11, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 510 kg"],
    ],
}


Toyota_CAMRY_2015 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY15"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "135 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2015"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "135 000 km"],
        ["Année", "03/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2015_1.jpg",
        "https://example.com/camry_2015_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsYkWYFs5RW",
    "model": "CAMRY",
    "price": 9800000,
    "kilometrage": 135000,
    "carburant": "Essence",
    "annee": date(2015, 3, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 520 kg"],
    ],
}

Toyota_CAMRY_2016 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY16"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2016"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "05/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
         "https://app.karborotech.net/carsis_seller_photos/Carsis_carsr3yyW9Jhv_01.jpg ",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsr3yyW9Jhv_02.jpg ",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsr3yyW9Jhv_03.jpg ",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsr3yyW9Jhv_04.jpg "
    ],
    "mark": "Toyota",
    "webid":  "Carsis_carsr3yyW9Jhv",
    "model": "CAMRY",
    "price": 10000000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2016, 5, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 530 kg"],
    ],
}

Toyota_CAMRY_2017 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY17"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "125 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2017"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "125 000 km"],
        ["Année", "07/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2017_1.jpg",
        "https://example.com/camry_2017_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsyqSUrVwWA",
    "model": "CAMRY",
    "price": 10500000,
    "kilometrage": 125000,
    "carburant": "Essence",
    "annee": date(2017, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 540 kg"],
    ],
}


Toyota_CAMRY_2018 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY18"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "155 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2018"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "09/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2018_1.jpg",
        "https://example.com/camry_2018_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsRqZP2dUZB",
    "model": "CAMRY",
    "price": 11000000,
    "kilometrage": 120000,
    "carburant": "Essence",
    "annee": date(2018, 9, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}

Toyota_CAMRY_2019 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY19"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,0l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2019"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "07/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/camry_2019_1.jpg",
        "https://example.com/camry_2019_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carslM9L1l7dM",
    "model": "CAMRY",
    "price": 11500000,
    "kilometrage": 110000,
    "carburant": "Essence",
    "annee": date(2019, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 560 kg"],
    ],
}

Toyota_CAMRY_2020 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY20"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "100 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2020"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "133 kW (180 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "100 000 km"],
        ["Année", "06/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
         "https://app.karborotech.net/carsis_seller_photos/Carsis_carsP2UDsVLga_01.jpg ",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsP2UDsVLga_02.jpg ",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsP2UDsVLga_03.jpg ",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsP2UDsVLga_04.jpg "
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsP2UDsVLga",
    "model": "CAMRY",
    "price": 12000000,
    "kilometrage": 100000,
    "carburant": "Essence",
    "annee": date(2020, 6, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "USA",
    "moteur": "2.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "133 kW (180 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 570 kg"],
    ],
}



Toyota_CAMRY=[Toyota_CAMRY_2009,Toyota_CAMRY_2013,Toyota_CAMRY_2016,Toyota_CAMRY_2020]