from datetime import date

 

Toyota_MATRIX_2007 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT07"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,8l/100 km (mixte)"],
        ["Émissions de CO2", "185 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "180 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "03/2007"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "180 000 km"],
        ["Année", "03/2007"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
         "https://app.karborotech.net/carsis_seller_photos/Carsis_carsx6trWuDGL_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsx6trWuDGL_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsx6trWuDGL_03.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsx6trWuDGL",
    "model": "MATRIX",
    "price": 7000000,
    "kilometrage": 180000,
    "carburant": "Essence",
    "annee": date(2007, 3, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 275 kg"],
    ],
}

Toyota_MATRIX_2008 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT08"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,6l/100 km (mixte)"],
        ["Émissions de CO2", "180 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "170 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2008"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "170 000 km"],
        ["Année", "06/2008"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/matrix_2008_1.jpg",
        "https://example.com/matrix_2008_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsMD2Eyxjow",
    "model": "MATRIX",
    "price": 7200000,
    "kilometrage": 170000,
    "carburant": "Essence",
    "annee": date(2008, 6, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 285 kg"],
    ],
}

Toyota_MATRIX_2009 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT09"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "175 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "165 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2009"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "165 000 km"],
        ["Année", "09/2009"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/matrix_2009_1.jpg",
        "https://example.com/matrix_2009_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsmpsKVarzJ",
    "model": "MATRIX",
    "price": 7400000,
    "kilometrage": 165000,
    "carburant": "Essence",
    "annee": date(2009, 9, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 290 kg"],
    ],
}


Toyota_MATRIX_2010 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT10"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,4l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2010"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2010"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
       "https://app.karborotech.net/carsis_seller_photos/Carsis_cars03CNKOE72_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars03CNKOE72_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars03CNKOE72_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars03CNKOE72_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars03CNKOE72",
    "model": "MATRIX",
    "price": 7600000,
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2010, 4, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 295 kg"],
    ],
}

Toyota_MATRIX_2011 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,3l/100 km (mixte)"],
        ["Émissions de CO2", "168 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "155 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "155 000 km"],
        ["Année", "06/2011"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/matrix_2011_1.jpg",
        "https://example.com/matrix_2011_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsuiv0SQlKV",
    "model": "MATRIX",
    "price": 7800000,
    "kilometrage": 155000,
    "carburant": "Essence",
    "annee": date(2011, 6, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 300 kg"],
    ],
}

Toyota_MATRIX_2012 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,2l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "08/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/matrix_2012_1.jpg",
        "https://example.com/matrix_2012_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars9UYhxQ9x2",
    "model": "MATRIX",
    "price": 8000000,
    "kilometrage": 150000,
    "carburant": "Essence",
    "annee": date(2012, 8, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 305 kg"],
    ],
}


Toyota_MATRIX_2013 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,1l/100 km (mixte)"],
        ["Émissions de CO2", "163 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "145 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "145 000 km"],
        ["Année", "05/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNjKP1VheQ_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNjKP1VheQ_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNjKP1VheQ_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsNjKP1VheQ_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsNjKP1VheQ",
    "model": "MATRIX",
    "price": 8200000,
    "kilometrage": 145000,
    "carburant": "Essence",
    "annee": date(2013, 5, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 310 kg"],
    ],
}

Toyota_MATRIX_2014 = {
    "basicData": [
        ["Carrosserie", "Break"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY_MAT14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "93 kW (126 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "07/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsxwXGWWmLL_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsxwXGWWmLL_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsxwXGWWmLL_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsxwXGWWmLL_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsxwXGWWmLL",
    "model": "MATRIX",
    "price": 8400000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2014, 7, 1),
    "carosserie": "Break",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "93 kW (126 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 315 kg"],
    ],
}


Toyota_MATRIX=[Toyota_MATRIX_2007,Toyota_MATRIX_2010,Toyota_MATRIX_2013,Toyota_MATRIX_2014]