from datetime import date




Toyota_COROLLA_2009 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR09"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,4l/100 km (mixte)"],
        ["Émissions de CO2", "175 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "170 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "04/2009"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "170 000 km"],
        ["Année", "04/2009"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carslx7ixxVSl_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carslx7ixxVSl_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carslx7ixxVSl_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carslx7ixxVSl_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carslx7ixxVSl",
    "model": "COROLLA",
    "price": 7000000,
    "kilometrage": 170000,
    "carburant": "Essence",
    "annee": date(2009, 4, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 280 kg"],
    ],
}

Toyota_COROLLA_2010 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR10"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,1l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "170 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2010"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "170 000 km"],
        ["Année", "06/2010"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2010_1.jpg",
        "https://example.com/corolla_2010_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carssgL0Eybe4",
    "model": "COROLLA",
    "price": 7200000,
    "kilometrage": 170000,
    "carburant": "Essence",
    "annee": date(2010, 6, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 290 kg"],
    ],
}

Toyota_COROLLA_2011 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "08/2011"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2011_1.jpg",
        "https://example.com/corolla_2011_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars5xXrpRGSm",
    "model": "COROLLA",
    "price": 7500000,
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2011, 8, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 295 kg"],
    ],
}

Toyota_COROLLA_2012 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,9l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "165 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "165 000 km"],
        ["Année", "03/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2012_1.jpg",
        "https://example.com/corolla_2012_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsiTbNVTqTO",
    "model": "COROLLA",
    "price": 7600000,
    "kilometrage": 165000,
    "carburant": "Essence",
    "annee": date(2012, 3, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 300 kg"],
    ],
}

Toyota_COROLLA_2013 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "158 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "05/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
       "https://app.karborotech.net/carsis_seller_photos/Carsis_carseGVSXBn9u_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseGVSXBn9u_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseGVSXBn9u_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carseGVSXBn9u_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsLfCQeyOfR",
    "model": "COROLLA",
    "price": 7800000,
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2013, 5, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 305 kg"],
    ],
}

Toyota_COROLLA_2014 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,7l/100 km (mixte)"],
        ["Émissions de CO2", "155 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "07/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2014_1.jpg",
        "https://example.com/corolla_2014_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsnZ4eILIit",
    "model": "COROLLA",
    "price": 8000000,
    "kilometrage": 150000,
    "carburant": "Essence",
    "annee": date(2014, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 310 kg"],
    ],
}
Toyota_COROLLA_2015 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR15"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,6l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "95 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2015"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "95 000 km"],
        ["Année", "09/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2015_1.jpg",
        "https://example.com/corolla_2015_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsqPU1nVRt0",
    "model": "COROLLA",
    "price": 8100000,
    "kilometrage": 95000,
    "carburant": "Essence",
    "annee": date(2015, 9, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 310 kg"],
    ],
}

Toyota_COROLLA_2016 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR16"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,4l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "90 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2016"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "90 000 km"],
        ["Année", "06/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
         "https://app.karborotech.net/carsis_seller_photos/Carsis_carsLfCQeyOfR_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsLfCQeyOfR_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsLfCQeyOfR_03.jpg"
        
    ],
    "mark": "Toyota",
    "webid": "Carsis_carseGVSXBn9u",
    "model": "COROLLA",
    "price": 8300000,
    "kilometrage": 90000,
    "carburant": "Essence",
    "annee": date(2016, 6, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 315 kg"],
    ],
}

Toyota_COROLLA_2017 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR17"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "140 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "85 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2017"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "97 kW (132 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "85 000 km"],
        ["Année", "09/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2017_1.jpg",
        "https://example.com/corolla_2017_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsnFmnSTzp9",
    "model": "COROLLA",
    "price": 8500000,
    "kilometrage": 85000,
    "carburant": "Essence",
    "annee": date(2017, 9, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "97 kW (132 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 320 kg"],
    ],
}

Toyota_COROLLA_2018 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR18"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,0l/100 km (mixte)"],
        ["Émissions de CO2", "138 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "90 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2018"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "103 kW (140 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "90 000 km"],
        ["Année", "03/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2018_1.jpg",
        "https://example.com/corolla_2018_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsUwt8v6t4K",
    "model": "COROLLA",
    "price": 8600000,
    "kilometrage": 90000,
    "carburant": "Essence",
    "annee": date(2018, 3, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "103 kW (140 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 340 kg"],
    ],
}

Toyota_COROLLA_2019 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR19"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "135 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "85 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2019"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "103 kW (140 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "85 000 km"],
        ["Année", "05/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/corolla_2019_1.jpg",
        "https://example.com/corolla_2019_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsVEB4bYZwD",
    "model": "COROLLA",
    "price": 8800000,
    "kilometrage": 85000,
    "carburant": "Essence",
    "annee": date(2019, 5, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "103 kW (140 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 345 kg"],
    ],
}

Toyota_COROLLA_2020 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_COR20"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,6l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "80 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2020"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "103 kW (140 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "80 000 km"],
        ["Année", "07/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
         "https://app.karborotech.net/carsis_seller_photos/Carsis_carsWsXHT4SAR_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsWsXHT4SAR_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsWsXHT4SAR_03.jpg",
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsWsXHT4SAR",
    "model": "COROLLA",
    "price": 9000000,
    "kilometrage": 80000,
    "carburant": "Essence",
    "annee": date(2020, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.8L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "103 kW (140 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 800 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 350 kg"],
    ],
}


Toyota_COROLLA=[Toyota_COROLLA_2009,Toyota_COROLLA_2013,Toyota_COROLLA_2016,Toyota_COROLLA_2020]