from datetime import date




Toyota_RAV4_Limited_2010 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY10-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,0l/100 km (mixte)"],
        ["Émissions de CO2", "185 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2010"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "135 kW (184 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2010"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars2M02uvJsY_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars2M02uvJsY_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars2M02uvJsY_03.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars2M02uvJsY",
    "model": "RAV4 Limited",
    "price": 7000000, 
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2010, 3, 1), 
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "135 kW (184 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 600 kg"],
    ],
}

Toyota_RAV4_Limited_2011 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY11-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,4l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2011"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "06/2011"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2011_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2011_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2011_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2011_Noir_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carswt2Zcz8u4",
    "model": "RAV4 Limited",
    "price": 7200000, 
    "kilometrage": 150000,
    "carburant": "Diesel",
    "annee":  date(2011, 5, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 650 kg"],
    ],
}


Toyota_RAV4_Limited_2012 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY12-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2012"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "07/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2012_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2012_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2012_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2012_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsbjQKl2yuK",
    "model": "RAV4 Limited",
    "price": 7400000,
    "kilometrage": 140000,
    "carburant": "Diesel",
    "annee": date(2012, 6, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color":  None,
    "colorData":  None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Toyota_RAV4_Limited_2013 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY13-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "09/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsQvcr6fWHM_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsQvcr6fWHM_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsQvcr6fWHM_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsQvcr6fWHM_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsQvcr6fWHM",
    "model": "RAV4 Limited",
    "price": 7600000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2013, 1, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color":  None,
    "colorData":  None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 750 kg"],
    ],
}


Toyota_RAV4_Limited_2014 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY14-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,2l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2014"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "07/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsG7wAHen0w",
    "model": "RAV4 Limited",
    "price": 7800000, 
    "kilometrage": 120000,
    "carburant": "Diesel",
    "annee": date(2014, 6, 1), 
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 750 kg"],
    ],
}

Toyota_RAV4_Limited_2015 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY15-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2014"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "07/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Limited_2014_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsbqFiULRbr",
    "model": "RAV4 Limited",
    "price": 7800000, 
    "kilometrage": 120000,
    "carburant": "Diesel",
    "annee": date(2014, 6, 1), 
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 750 kg"],
    ],
}

Toyota_RAV4_Limited_2016 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY16-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Hybride"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Panoramique"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2016"],
        ["Carburant", "Hybride"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "09/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsbqFiULRbr_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsbqFiULRbr_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsbqFiULRbr_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsbqFiULRbr_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsEVXCEMvsO",
    "model": "RAV4 Limited",
    "price": 7000000,
    "kilometrage": 120000,
    "carburant": "Hybride",
    "annee": date(2016, 8, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.5L Hybrid",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}


Toyota_RAV4_Limited_2017 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY16-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Hybride"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Panoramique"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2016"],
        ["Carburant", "Hybride"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "02/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carshZcwybw21",
    "model": "RAV4 Limited",
    "price": 7000000,
    "kilometrage": 130000,
    "carburant": "Hybride",
    "annee": date(2017, 2, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.5L Hybrid",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Toyota_RAV4_Limited_2018 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY16-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Hybride"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Panoramique"],
    ],
    "generalValues": [
        ["Kilométrage", "115 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2018"],
        ["Carburant", "Hybride"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "115 000 km"],
        ["Année", "04/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsrXKegTNqx",
    "model": "RAV4 Limited",
    "price": 7000000,
    "kilometrage": 115000,
    "carburant": "Hybride",
    "annee": date(2018, 4, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.5L Hybrid",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}



Toyota_RAV4_Limited_2019 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY16-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Hybride"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Panoramique"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2019"],
        ["Carburant", "Hybride"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "04/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsy9rh3jG4z_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsy9rh3jG4z_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsy9rh3jG4z_03.jpg",
       
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsy9rh3jG4z",
    "model": "RAV4 Limited",
    "price": 7000000,
    "kilometrage": 110000,
    "carburant": "Hybride",
    "annee": date(2019, 4, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.5L Hybrid",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}




Toyota_RAV4_Limited_2020 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY16-LIM"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Hybride"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Panoramique"],
    ],
    "generalValues": [
        ["Kilométrage", "105 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2020"],
        ["Carburant", "Hybride"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "105 000 km"],
        ["Année", "03/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_2016_Blanc_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars6RYeMwRIw",
    "model": "RAV4 Limited",
    "price": 7000000,
    "kilometrage": 105000,
    "carburant": "Hybride",
    "annee": date(2020, 3, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.5L Hybrid",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Toyota_RAV4_Limited=[Toyota_RAV4_Limited_2010,Toyota_RAV4_Limited_2013,Toyota_RAV4_Limited_2016,Toyota_RAV4_Limited_2019]