from datetime import date



Toyota_YARIS_SEDAN_2007 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR07"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "153 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "180 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "04/2007"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "180 000 km"],
        ["Année", "04/2007"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
          "https://app.karborotech.net/carsis_seller_photos/Carsis_cars1uuG91Y33_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars1uuG91Y33_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars1uuG91Y33_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars1uuG91Y33_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars1uuG91Y33",
    "model": "YARIS SEDAN",
    "price": 6500000,
    "kilometrage": 180000,
    "carburant": "Essence",
    "annee": date(2007, 4, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 050 kg"],
    ],
}

Toyota_YARIS_SEDAN_2008 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR08"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,4l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "170 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "05/2008"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "170 000 km"],
        ["Année", "05/2008"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2008_1.jpg",
        "https://example.com/yaris_sedan_2008_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsulk7mqfOI",
    "model": "YARIS SEDAN",
    "price": 6700000,
    "kilometrage": 170000,
    "carburant": "Essence",
    "annee": date(2008, 5, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 060 kg"],
    ],
}

Toyota_YARIS_SEDAN_2009 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR09"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,3l/100 km (mixte)"],
        ["Émissions de CO2", "148 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "165 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2009"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "165 000 km"],
        ["Année", "07/2009"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2009_1.jpg",
        "https://example.com/yaris_sedan_2009_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsu5hFTpR5n",
    "model": "YARIS SEDAN",
    "price": 6900000,
    "kilometrage": 165000,
    "carburant": "Essence",
    "annee": date(2009, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 070 kg"],
    ],
}

Toyota_YARIS_SEDAN_2010 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR10"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2010"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2010"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
          "https://app.karborotech.net/carsis_seller_photos/Carsis_carsDCNh3IFhF_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsDCNh3IFhF_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsDCNh3IFhF_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsDCNh3IFhF_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsDCNh3IFhF",
    "model": "YARIS SEDAN",
    "price": 7100000,
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2010, 4, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 075 kg"],
    ],
}

Toyota_YARIS_SEDAN_2011 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,1l/100 km (mixte)"],
        ["Émissions de CO2", "144 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "155 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "155 000 km"],
        ["Année", "06/2011"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2011_1.jpg",
        "https://example.com/yaris_sedan_2011_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsP4aJFstOZ",
    "model": "YARIS SEDAN",
    "price": 7300000,
    "kilometrage": 155000,
    "carburant": "Essence",
    "annee": date(2011, 6, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 080 kg"],
    ],
}

Toyota_YARIS_SEDAN_2012 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,0l/100 km (mixte)"],
        ["Émissions de CO2", "140 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "09/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2012_1.jpg",
        "https://example.com/yaris_sedan_2012_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars2Mi1IRzIg",
    "model": "YARIS SEDAN",
    "price": 7500000,
    "kilometrage": 140000,
    "carburant": "Essence",
    "annee": date(2012, 9, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 085 kg"],
    ],
}
Toyota_YARIS_SEDAN_2013 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,0l/100 km (mixte)"],
        ["Émissions de CO2", "140 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "135 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "135 000 km"],
        ["Année", "03/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrpMOIgyfu_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrpMOIgyfu_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrpMOIgyfu_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsrpMOIgyfu_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsrpMOIgyfu",
    "model": "YARIS SEDAN",
    "price": 7700000,
    "kilometrage": 135000,
    "carburant": "Essence",
    "annee": date(2013, 3, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 090 kg"],
    ],
}

Toyota_YARIS_SEDAN_2014 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,9l/100 km (mixte)"],
        ["Émissions de CO2", "138 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "06/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2014_1.jpg",
        "https://example.com/yaris_sedan_2014_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsnz2fbrfMS",
    "model": "YARIS SEDAN",
    "price": 7900000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2014, 6, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 095 kg"],
    ],
}

Toyota_YARIS_SEDAN_2015 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR15"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,8l/100 km (mixte)"],
        ["Émissions de CO2", "135 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "125 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2015"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "125 000 km"],
        ["Année", "08/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2015_1.jpg",
        "https://example.com/yaris_sedan_2015_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carseFEBpyNsK",
    "model": "YARIS SEDAN",
    "price": 8100000,
    "kilometrage": 125000,
    "carburant": "Essence",
    "annee": date(2015, 8, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 100 kg"],
    ],
}

Toyota_YARIS_SEDAN_2016 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR16"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,7l/100 km (mixte)"],
        ["Émissions de CO2", "130 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2016"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "03/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
         "https://app.karborotech.net/carsis_seller_photos/Carsis_cars26MfXmclm_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars26MfXmclm_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars26MfXmclm_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars26MfXmclm_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars26MfXmclm",
    "model": "YARIS SEDAN",
    "price": 8200000,
    "kilometrage": 120000,
    "carburant": "Essence",
    "annee": date(2016, 3, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 100 kg"],
    ],
}

Toyota_YARIS_SEDAN_2017 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR17"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,6l/100 km (mixte)"],
        ["Émissions de CO2", "125 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "105 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2017"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "105 000 km"],
        ["Année", "05/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2017_1.jpg",
        "https://example.com/yaris_sedan_2017_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsxJNJRRhSC",
    "model": "YARIS SEDAN",
    "price": 8400000,
    "kilometrage": 105000,
    "carburant": "Essence",
    "annee": date(2017, 5, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 105 kg"],
    ],
}

Toyota_YARIS_SEDAN_2018 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR18"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,5l/100 km (mixte)"],
        ["Émissions de CO2", "120 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "90 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2018"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "90 000 km"],
        ["Année", "08/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2018_1.jpg",
        "https://example.com/yaris_sedan_2018_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_cars6tIzccWHG",
    "model": "YARIS SEDAN",
    "price": 8600000,
    "kilometrage": 90000,
    "carburant": "Essence",
    "annee": date(2018, 8, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 110 kg"],
    ],
}


Toyota_YARIS_SEDAN_2019 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR19"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,4l/100 km (mixte)"],
        ["Émissions de CO2", "118 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "85 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2019"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "85 000 km"],
        ["Année", "04/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2019_1.jpg",
        "https://example.com/yaris_sedan_2019_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsY97KZIdeV",
    "model": "YARIS SEDAN",
    "price": 8800000,
    "kilometrage": 85000,
    "carburant": "Essence",
    "annee": date(2019, 4, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 115 kg"],
    ],
}

Toyota_YARIS_SEDAN_2020 = {
    "basicData": [
        ["Carrosserie", "Berline"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/TOY_YAR20"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "5,3l/100 km (mixte)"],
        ["Émissions de CO2", "115 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "60 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2020"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "80 kW (109 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "60 000 km"],
        ["Année", "07/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://example.com/yaris_sedan_2020_1.jpg",
        "https://example.com/yaris_sedan_2020_2.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsJqV3B6MHl",
    "model": "YARIS SEDAN",
    "price": 9000000,
    "kilometrage": 60000,
    "carburant": "Essence",
    "annee": date(2020, 7, 1),
    "carosserie": "Berline",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "1.5L 4-cylindres",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "80 kW (109 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "1 500 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 120 kg"],
    ],
}


Toyota_YARIS_SEDAN=[Toyota_YARIS_SEDAN_2007,Toyota_YARIS_SEDAN_2010,Toyota_YARIS_SEDAN_2013,Toyota_YARIS_SEDAN_2016]