from datetime import date






Hyundai_SANTA_FE_2010 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "175 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2010"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "03/2010"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2010_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2010_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2010_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2010_Noir_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carsc79Vdca7n",
    "model": "SANTA FE",
    "price": 7000000,
    "kilometrage": 150000,
    "carburant": "Diesel",
    "annee": date(2010, 3, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 800 kg"],
    ],
}

Hyundai_SANTA_FE_2011 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF1"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,3l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "05/2011"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "155 kW (211 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "05/2011"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2011_Bleu_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2011_Bleu_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2011_Bleu_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2011_Bleu_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carsWvCndTx5J",
    "model": "SANTA FE",
    "price": 7200000,
    "kilometrage": 140000,
    "carburant": "Diesel",
    "annee": date(2011, 5, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Bleu",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "155 kW (211 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 820 kg"],
    ],
}

Hyundai_SANTA_FE_2012 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF2"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,0l/100 km (mixte)"],
        ["Émissions de CO2", "185 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "07/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "07/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2012_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2012_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2012_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2012_Gris_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carswSLeZ4JOT",
    "model": "SANTA FE",
    "price": 7500000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2012, 7, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte manuelle",
    "color": "Gris",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 750 kg"],
    ],
}

Hyundai_SANTA_FE_2013 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF3"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,1l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2013"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "09/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsiKbDHVinu_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsiKbDHVinu_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsiKbDHVinu_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsiKbDHVinu_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carsiKbDHVinu",
    "model": "SANTA FE",
    "price": 7800000,
    "kilometrage": 120000,
    "carburant": "Diesel",
    "annee": date(2013, 9, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 850 kg"],
    ],
}

Hyundai_SANTA_FE_2014 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF4"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,8l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "11/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "145 kW (197 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "11/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2014_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2014_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2014_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2014_Rouge_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carsvIhoybur5",
    "model": "SANTA FE",
    "price": 8000000,
    "kilometrage": 110000,
    "carburant": "Essence",
    "annee": date(2014, 11, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "145 kW (197 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 800 kg"],
    ],
}

from datetime import date

Hyundai_SANTA_FE_2015 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF5"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,2l/100 km (mixte)"],
        ["Émissions de CO2", "168 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2015"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "04/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2015_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2015_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2015_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2015_Noir_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carstCeWu6oHm",
    "model": "SANTA FE",
    "price": 7500000,
    "kilometrage": 130000,
    "carburant": "Diesel",
    "annee": date(2015, 4, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 850 kg"],
    ],
}

Hyundai_SANTA_FE_2016 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF6"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,1l/100 km (mixte)"],
        ["Émissions de CO2", "180 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système audio premium", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "125 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "06/2016"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "125 000 km"],
        ["Année", "06/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars4UspG6mge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars4UspG6mge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars4UspG6mge_03.jpg",
       
    ],
    "mark": "Hyundai",
    "webid": "Carsis_cars4UspG6mge",
    "model": "SANTA FE",
    "price": 7800000,
    "kilometrage": 125000,
    "carburant": "Essence",
    "annee": date(2016, 6, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte manuelle",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 820 kg"],
    ],
}

Hyundai_SANTA_FE_2017 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF7"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
        ["Système de sécurité avancé", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2017"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "08/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2017_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2017_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2017_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2017_Blanc_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carsTAhXnl2PI",
    "model": "SANTA FE",
    "price": 8000000,
    "kilometrage": 120000,
    "carburant": "Diesel",
    "annee": date(2017, 8, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 850 kg"],
    ],
}

Hyundai_SANTA_FE_2018 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF8"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,9l/100 km (mixte)"],
        ["Émissions de CO2", "158 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "115 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "10/2018"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "155 kW (211 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "115 000 km"],
        ["Année", "10/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2018_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2018_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2018_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2018_Rouge_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_cars6E4NQDuoh",
    "model": "SANTA FE",
    "price": 8200000,
    "kilometrage": 115000,
    "carburant": "Essence",
    "annee": date(2018, 10, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "155 kW (211 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 800 kg"],
    ],
}

Hyundai_SANTA_FE_2019 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF9"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "12/2019"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "170 kW (231 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "12/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2019_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2019_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2019_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Hyundai_SANTA_FE_2019_Noir_04.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_carsU0gQuzxjW",
    "model": "SANTA FE",
    "price": 8500000,
    "kilometrage": 110000,
    "carburant": "Diesel",
    "annee": date(2019, 12, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "170 kW (231 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 900 kg"],
    ],
}

Hyundai_SANTA_FE_2020 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/ASF0"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "100 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2020"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "175 kW (238 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "100 000 km"],
        ["Année", "02/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars3dnMTEsI0_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars3dnMTEsI0_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars3dnMTEsI0_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars3dnMTEsI0_04.jpg.jpg"
    ],
    "mark": "Hyundai",
    "webid": "Carsis_cars3dnMTEsI0",
    "model": "SANTA FE",
    "price": 8800000,
    "kilometrage": 100000,
    "carburant": "Essence",
    "annee": date(2020, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "175 kW (238 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 900 kg"],
    ],
}



Hyundai_SANTA_FE=[Hyundai_SANTA_FE_2013,Hyundai_SANTA_FE_2016,Hyundai_SANTA_FE_2020]