from datetime import date





Toyota_RAV4_Sport_2010 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "170 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "04/2010"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "170 000 km"],
        ["Année", "04/2010"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjPl33eCX8_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjPl33eCX8_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjPl33eCX8_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjPl33eCX8_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsjPl33eCX8",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 170000,
    "carburant": "Essence",
    "annee": date(2010, 4, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2011 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "05/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "05/2011"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsUnw6Toc6R",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2011, 5, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}




Toyota_RAV4_Sport_2012 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "155 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "05/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "155 000 km"],
        ["Année", "05/2012"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsLno3jlJx3",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 155000,
    "carburant": "Essence",
    "annee": date(2012, 5, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte manuelle",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2013 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "04/2013"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "04/2013"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsQOu5xFLIE",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 150000,
    "carburant": "Essence",
    "annee": date(2013, 4, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}

Toyota_RAV4_Sport_2014 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "145 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "145 000 km"],
        ["Année", "06/2014"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsdHBG1pw9S",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 145000,
    "carburant": "Essence",
    "annee": date(2014, 6, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2015 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "142 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2015"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "142 000 km"],
        ["Année", "07/2015"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsFuiJhr7sn",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 142000,
    "carburant": "Essence",
    "annee": date(2015, 7, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2016 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "138 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2016"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "138 000 km"],
        ["Année", "08/2016"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsmeP0bTA59",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 138000,
    "carburant": "Essence",
    "annee": date(2016, 8, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2017 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "135 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2017"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "135 000 km"],
        ["Année", "09/2017"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsBqlGPG0pW",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 135000,
    "carburant": "Essence",
    "annee": date(2017, 9, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2018 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "133 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2018"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "133 000 km"],
        ["Année", "08/2018"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsdNCmQSwdQ",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 133000,
    "carburant": "Essence",
    "annee": date(2018, 8, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}




Toyota_RAV4_Sport_2019 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "11/2019"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "11/2019"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carspCmuZDnae",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 120000,
    "carburant": "Essence",
    "annee": date(2019, 11, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}

Toyota_RAV4_Sport_2020 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "115 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "10/2020"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "115 000 km"],
        ["Année", "10/2020"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsCbejtxFQm",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 115000,
    "carburant": "Essence",
    "annee": date(2020, 10, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2021 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "95 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2021"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "95 000 km"],
        ["Année", "02/2021"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsqoEwWaORR",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 95000,
    "carburant": "Essence",
    "annee": date(2021, 2, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}


Toyota_RAV4_Sport_2022 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "5"],
        ["Numéro de la touche", "5013/TOY09-SPT"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 4"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "198 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "90 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2022"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "125 kW (170 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "90 000 km"],
        ["Année", "03/2022"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsToyota_RAV4_Sport_2009_Gris_04.jpg"
    ],
    "mark": "Toyota",
    "webid": "Carsis_carsepcJCtW1t",
    "model": "RAV4 Sport",
    "price": 6500000, 
    "kilometrage": 95000,
    "carburant": "Essence",
    "annee": date(2022, 3, 1),
    "carosserie": "SUV/4x4",
    "sieges": "5",
    "portes": "5",
    "pays": "Canada",
    "moteur": "2.4L VVT-i",
    "transmission": "Boîte automatique",
    "color": None,
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "125 kW (170 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 400 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}



Toyota_RAV4_Sport=[Toyota_RAV4_Sport_2010]  #,Toyota_RAV4_Sport_2013,Toyota_RAV4_Sport_2016,Toyota_RAV4_Sport_2020,Toyota_RAV4_Sport_2022
