from datetime import date


 
Kia_OPTIMA_2011 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,5l/100 km (mixte)"],
        ["Émissions de CO2", "190 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "04/2011"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "120 kW (163 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2011"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carst5f4U74bZ_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carst5f4U74bZ_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carst5f4U74bZ_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carst5f4U74bZ_04.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carst5f4U74bZ_05.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carst5f4U74bZ",
    "model": "OPTIMA",
    "price": 6000000,
    "kilometrage": 160000,
    "carburant": "Essence",
    "annee": date(2011, 4, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte manuelle",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "120 kW (163 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 350 kg"],
    ],
}

Kia_OPTIMA_2012 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,8l/100 km (mixte)"],
        ["Émissions de CO2", "175 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2012"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "06/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2012_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2012_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2012_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2012_Rouge_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsdmhYqrp0J",
    "model": "OPTIMA",
    "price": 6500000,
    "kilometrage": 150000,
    "carburant": "Diesel",
    "annee": date(2012, 6, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 380 kg"],
    ],
}

Kia_OPTIMA_2013 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
        ["Système de sécurité avancé", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2013"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "09/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjc35lGDNK_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjc35lGDNK_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsjc35lGDNK_03.jpg",
        
    ],
    "mark": "Kia",
    "webid": "Carsis_carsjc35lGDNK",
    "model": "OPTIMA",
    "price": 6800000,
    "kilometrage": 140000,
    "carburant": "Diesel",
    "annee": date(2013, 9, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 400 kg"],
    ],
}

Kia_OPTIMA_2014 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "11/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "11/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2014_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2014_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2014_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2014_Rouge_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carstDc7tjDDu",
    "model": "OPTIMA",
    "price": 7000000,
    "kilometrage": 130000,
    "carburant": "Essence",
    "annee": date(2014, 11, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 420 kg"],
    ],
}

Kia_OPTIMA_2015 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA15"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2015"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "02/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2015_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2015_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2015_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2015_Blanc_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsFWooNKS7N",
    "model": "OPTIMA",
    "price": 7200000,
    "kilometrage": 120000,
    "carburant": "Essence",
    "annee": date(2015, 2, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 450 kg"],
    ],
}

Kia_OPTIMA_2016 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA16"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,5l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2016"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "150 kW (204 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "02/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsAzyKmgXIX_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsAzyKmgXIX_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsAzyKmgXIX_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsAzyKmgXIX_04.jpg.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsAzyKmgXIX",
    "model": "OPTIMA",
    "price": 7500000,
    "kilometrage": 120000,
    "carburant": "Essence",
    "annee": date(2016, 2, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "150 kW (204 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 450 kg"],
    ],
}

Kia_OPTIMA_2017 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA17"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,9l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "115 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "08/2017"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "115 000 km"],
        ["Année", "08/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2017_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2017_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2017_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2017_Noir_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_cars0gVMaqOx2",
    "model": "OPTIMA",
    "price": 7800000,
    "kilometrage": 115000,
    "carburant": "Diesel",
    "annee": date(2017, 8, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 500 kg"],
    ],
}

Kia_OPTIMA_2018 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA18"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "10/2018"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "155 kW (211 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "10/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2018_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2018_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2018_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2018_Rouge_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsnxZEcgGSR",
    "model": "OPTIMA",
    "price": 8200000,
    "kilometrage": 110000,
    "carburant": "Essence",
    "annee": date(2018, 10, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "155 kW (211 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 500 kg"],
    ],
}

Kia_OPTIMA_2019 = {
    "basicData": [
        ["Carrosserie", "Berline/Sedan"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA19"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "100 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "12/2019"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "170 kW (231 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "100 000 km"],
        ["Année", "12/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2019_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2019_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2019_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_OPTIMA_2019_Noir_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsU6gb0cubd",
    "model": "OPTIMA",
    "price": 8500000,
    "kilometrage": 100000,
    "carburant": "Diesel",
    "annee": date(2019, 12, 1),
    "carosserie": "Berline/Sedan",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "170 kW (231 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 600 kg"],
    ],
}



Kia_OPTIMA=[Kia_OPTIMA_2011,Kia_OPTIMA_2013,Kia_OPTIMA_2016]