from datetime import date




Kia_SPORTAGE_2010 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA10"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,4l/100 km (mixte)"],
        ["Émissions de CO2", "170 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Manuelle"],
        ["Système de navigation", "Non"],
        ["Caméra de recul", "Non"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "160 000 km"],
        ["Transmission", "Boîte manuelle"],
        ["Année", "04/2010"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "130 kW (177 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "160 000 km"],
        ["Année", "04/2010"],
        ["Propriétaires préc.", "2"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsWHAn3A2kk_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsWHAn3A2kk_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsWHAn3A2kk_03.jpg"
        
    ],
    "mark": "Kia",
    "webid": "Carsis_carsWHAn3A2kk",
    "model": "SPORTAGE",
    "price": 6500000,
    "kilometrage": 160000,
    "carburant": "Diesel",
    "annee": date(2010, 4, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L CRDi",
    "transmission": "Boîte manuelle",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "130 kW (177 CH)"],
        ["Transmission", "Boîte manuelle"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 500 kg"],
    ],
}

Kia_SPORTAGE_2011 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA11"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 5"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "7,0l/100 km (mixte)"],
        ["Émissions de CO2", "160 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Non"],
    ],
    "generalValues": [
        ["Kilométrage", "150 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "06/2011"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "140 kW (190 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "150 000 km"],
        ["Année", "06/2011"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2011_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2011_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2011_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2011_Rouge_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsnms4PfaIv",
    "model": "SPORTAGE",
    "price": 6700000,
    "kilometrage": 150000,
    "carburant": "Diesel",
    "annee": date(2011, 6, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "140 kW (190 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 550 kg"],
    ],
}

Kia_SPORTAGE_2012 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA12"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "8,2l/100 km (mixte)"],
        ["Émissions de CO2", "185 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système audio premium", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "140 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "07/2012"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "145 kW (197 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "140 000 km"],
        ["Année", "07/2012"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2012_Gris_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2012_Gris_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2012_Gris_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2012_Gris_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsl9WHRq7np",
    "model": "SPORTAGE",
    "price": 6900000,
    "kilometrage": 140000,
    "carburant": "Essence",
    "annee": date(2012, 7, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Gris",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "145 kW (197 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 600 kg"],
    ],
}

Kia_SPORTAGE_2013 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA13"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "130 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "09/2013"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "160 kW (218 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "130 000 km"],
        ["Année", "09/2013"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars7HGzsJEP7_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars7HGzsJEP7_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars7HGzsJEP7_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars7HGzsJEP7_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_cars7HGzsJEP7",
    "model": "SPORTAGE",
    "price": 7100000,
    "kilometrage": 130000,
    "carburant": "Diesel",
    "annee": date(2013, 9, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Bleu",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "160 kW (218 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 650 kg"],
    ],
}

Kia_SPORTAGE_2014 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA14"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,2l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "11/2014"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "155 kW (211 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "11/2014"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2014_Rouge_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2014_Rouge_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2014_Rouge_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2014_Rouge_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsM3HBxkk28",
    "model": "SPORTAGE",
    "price": 7300000,
    "kilometrage": 120000,
    "carburant": "Essence",
    "annee": date(2014, 11, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "155 kW (211 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 600 kg"],
    ],
}

Kia_SPORTAGE_2015 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA15"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2015"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "165 kW (224 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "02/2015"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2015_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2015_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2015_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2015_Blanc_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsPnePLlp3j",
    "model": "SPORTAGE",
    "price": 7500000,
    "kilometrage": 110000,
    "carburant": "Diesel",
    "annee": date(2015, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "165 kW (224 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

from datetime import date

Kia_SPORTAGE_2016 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA16"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,8l/100 km (mixte)"],
        ["Émissions de CO2", "150 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "120 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2016"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "165 kW (224 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "120 000 km"],
        ["Année", "02/2016"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsEIfuoZu0t_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsEIfuoZu0t_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsEIfuoZu0t_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carsEIfuoZu0t_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsEIfuoZu0t",
    "model": "SPORTAGE",
    "price": 7500000,
    "kilometrage": 120000,
    "carburant": "Diesel",
    "annee": date(2016, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "165 kW (224 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 700 kg"],
    ],
}

Kia_SPORTAGE_2017 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA17"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "7,2l/100 km (mixte)"],
        ["Émissions de CO2", "165 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "110 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2017"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "170 kW (231 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "110 000 km"],
        ["Année", "02/2017"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2017_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2017_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2017_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2017_Blanc_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsc1kccLJUK",
    "model": "SPORTAGE",
    "price": 7800000,
    "kilometrage": 110000,
    "carburant": "Essence",
    "annee": date(2017, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "170 kW (231 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 750 kg"],
    ],
}

Kia_SPORTAGE_2018 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA18"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,5l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "100 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "02/2018"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "175 kW (238 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "100 000 km"],
        ["Année", "02/2018"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2018_Blanc_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2018_Blanc_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2018_Blanc_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2018_Blanc_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carshjRkMn4ES",
    "model": "SPORTAGE",
    "price": 8200000,
    "kilometrage": 100000,
    "carburant": "Diesel",
    "annee": date(2018, 2, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Blanc",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "175 kW (238 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 800 kg"],
    ],
}

Kia_SPORTAGE_2019 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA19"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Essence"],
        ["Consommation de carburant", "6,2l/100 km (mixte)"],
        ["Émissions de CO2", "145 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "90 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "12/2019"],
        ["Carburant", "Essence"],
        ["Puissance kW (CH)", "180 kW (245 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "90 000 km"],
        ["Année", "12/2019"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2019_Noir_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2019_Noir_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2019_Noir_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_cars_Kia_SPORTAGE_2019_Noir_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carsBQVsOvo3s",
    "model": "SPORTAGE",
    "price": 8500000,
    "kilometrage": 90000,
    "carburant": "Essence",
    "annee": date(2019, 12, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.0L GDi",
    "transmission": "Boîte automatique",
    "color": "Noir",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "180 kW (245 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 000 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 850 kg"],
    ],
}

Kia_SPORTAGE_2020 = {
    "basicData": [
        ["Carrosserie", "SUV/4x4/Pick-Up"],
        ["État", "Occasion"],
        ["Sièges", "5"],
        ["Portes", "4"],
        ["Numéro de la touche", "5013/KIA20"],
    ],
    "energieData": [
        ["Classe d'émission", "Euro 6"],
        ["Carburant", "Diesel"],
        ["Consommation de carburant", "6,0l/100 km (mixte)"],
        ["Émissions de CO2", "140 g/km (mixte)"],
    ],
    "equipement": [
        ["Climatisation", "Automatique"],
        ["Système de navigation", "Oui"],
        ["Caméra de recul", "Oui"],
        ["Toit ouvrant", "Oui"],
        ["Système de sécurité avancé", "Oui"],
        ["Connectivité Bluetooth", "Oui"],
        ["Chargeur USB", "Oui"],
        ["Système audio premium", "Oui"],
    ],
    "generalValues": [
        ["Kilométrage", "80 000 km"],
        ["Transmission", "Boîte automatique"],
        ["Année", "03/2020"],
        ["Carburant", "Diesel"],
        ["Puissance kW (CH)", "185 kW (252 CH)"],
    ],
    "historicalData": [
        ["Kilométrage", "80 000 km"],
        ["Année", "03/2020"],
        ["Propriétaires préc.", "1"],
        ["Carnet d'entretien", "Oui"],
    ],
    "image_urls": [
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carshuGLL6uc9_01.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carshuGLL6uc9_02.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carshuGLL6uc9_03.jpg",
        "https://app.karborotech.net/carsis_seller_photos/Carsis_carshuGLL6uc9_04.jpg"
    ],
    "mark": "Kia",
    "webid": "Carsis_carshuGLL6uc9",
    "model": "SPORTAGE",
    "price": 8800000,
    "kilometrage": 80000,
    "carburant": "Diesel",
    "annee": date(2020, 3, 1),
    "carosserie": "SUV/4x4/Pick-Up",
    "sieges": "5",
    "portes": "4",
    "pays": "Canada",
    "moteur": "2.2L CRDi",
    "transmission": "Boîte automatique",
    "color": "Rouge",
    "colorData": None,
    "technicaData": [
        ["Puissance kW (CH)", "185 kW (252 CH)"],
        ["Transmission", "Boîte automatique"],
        ["Cylindrée", "2 200 cm³"],
        ["Cylindres", "4"],
        ["Poids à vide", "1 900 kg"],
    ],
}




Kia_SPORTAGE=[Kia_SPORTAGE_2010,Kia_SPORTAGE_2013,Kia_SPORTAGE_2016,Kia_SPORTAGE_2020]